config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # mount_devise_token_auth_for 'User', at: 'users', controllers: {
      #   registrations: 'api/v1/users/registrations',
      #   sessions: 'api/v1/users/sessions'
      # }

      resources :items, except: %I[new edit] do
        resources :photos, except: %I[new edit]
      end
    end
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :properties
    resources :stores
    resources :users

    root 'home#index'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callback: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :items, only: %I[index show] do
    collection do
      get :me
      get :following
    end

    resources :photos, module: 'items'
  end
  resources :stores do
    resources :items, module: 'stores'
  end
  resource :account, only: %I[show edit update]
  resource :profile
  resource :setting

  root 'items#index'
end

app/models/store.rb
# frozen_string_literal: true

# Store model
class Store < ApplicationRecord
  include ActivityControl

  belongs_to :user

  has_many :items, dependent: :destroy
  has_many :labels, through: :items
  has_many :categories, through: :items, class_name: 'Category'

  has_one_attached :avatar do |attachable|
    attachable.variant :small, resize: '80x80'
  end

  validates :avatar, blob: { content_type: :image, size_range: 1..5.megabytes }
  # validates :name, :domain_name, uniqueness: true, presence: true
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

module Admin
  # StoresController
  class StoresController < Admin::ApplicationController
    include Pagination

    def index
      @search = Store.ransack(query)
      @stores = @search.result(distinct: true)
                       .page(page)
                       .per(per_page)
                       .order(order)

      respond_to do |format|
        format.html
        format.js
      end
    end

    def show
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html
        format.js
      end
    end

    def new
      @store = Store.new
    end

    def create
      @store = Store.new(store_params)

      respond_to do |format|
        if @store.save
          format.html { redirect_to admin_stores_path, notice: t('.success') }
        else
          format.html { render :new, notice: t('.failed') }
        end
      end
    end

    def edit
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html
        format.js
      end
    end

    def update
      @store = Store.find(params[:id])

      respond_to do |format|
        if @store.update(store_params)
          format.html { redirect_to admin_stores_path, notice: t('.success') }
        else
          format.html { render :edit, notice: t('.failed') }
        end
      end
    end

    def destroy
      @store = Store.find(params[:id])

      respond_to do |format|
        if @store.destroy
          format.html { redirect_to admin_stores_path }
        else
          format.html { redirect_to admin_store_path(@store) }
        end
      end
    end

    private

    def store_params
      params.require(:store).permit(:user_id, :name, :description, :domain_name, :avatar)
    end
  end
end

app/controllers/stores/items_controller.rb
# frozen_string_literal: true

module Stores
  # ItemsController
  class ItemsController < ApplicationController
    include Pagination

    before_action :authenticate_user!
    before_action :find_store, except: :index

    def index
      @store = Store.where(id: params[:store_id]).first

      redirect_to stores_path and return unless @store

      @search = @store.items.ransack(query)
      @items = @search.result(distinct: true)
                      .order(order)
                      .page(page)
                      .per(per_page)
    end

    def show
      @item = @store.items.find(params[:id])

      render 'items/show'
    end

    def new
      @item = @store.items.new

      render partial: 'stores/items/form' if request.xhr?
    end

    def create
      @item = @store.items.new(item_params)

      if @item.save
        redirect_to store_path(@store), notice: t('items.create.success')
      else
        render partial: 'stores/items/form', status: :unprocessable_entity and return if request.xhr?

        render :new
      end
    end

    def edit
      @item = @store.items.find(params[:id])

      render partial: 'stores/items/form' if request.xhr?
    end

    def update
      @item = @store.items.find(params[:id])

      if @item.update(item_params)
        if request.xhr?
          render partial: 'stores/items/form'
        else
          redirect_to store_path(@store), notice: t('items.update.success')
        end
      elsif request.xhr?
        render partial: 'stores/items/form'
      else
        render :edit
      end
    end

    def destroy
      @item = @store.items.find(params[:id])

      notice = @item.destroy ? t('items.destroy.success') : t('items.destroy.failed')

      redirect_to store_path(@store), notice: notice
    end

    private

    def item_params
      params.require(:item).permit(
        :name,
        :description,
        :category_id,
        :label_id,
        item_labels_attributes: %i[id label_id _destroy],
        photos: []
      )
    end

    def find_store
      @store = current_user.stores.where(id: params[:store_id]).first

      respond_to do |format|
        format.html { redirect_to stores_path and return unless @store }
      end
    end
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

# StoresController
class StoresController < ApplicationController
  include Pagination

  before_action :authenticate_user!

  def index
    @search = current_user.stores.ransack(query)

    @stores = @search.result(distinct: true)
                     .order(order)
                     .page(page)
                     .per(per_page)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @store = current_user.stores.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @store = current_user.stores.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_path, notice: t('stores.create.success') }
        format.js { render json: @store.to_json }
      else
        format.html { render :new }
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @store = current_user.stores.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @store = current_user.stores.find(params[:id])
    store_params.delete(:domain_name)

    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to previous_or_current_path(store_path(@store)), notice: t('stores.update.success') }
        format.js { render json: @store.to_json }
      else
        format.html { render :edit }
        format.js { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store = current_user.stores.find(params[:id])

    respond_to do |format|
      if @store.destroy
        format.html { redirect_to stores_path, notice: t('stores.destroy.success') }
      else
        format.html { render stores_path }
      end
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :domain_name, :description, :avatar)
  end
end

app/views/stores/_form.html.erb
<%= form_with model: @store, local: local, url: url, builder: BerjubelFormBuilder,
  data: { 'bj-remote': !local, 'bj-processor': 'store/validate-form' } do |f| %>

  <%= f.alert %>
  <%= f.text_form_group :name %>

  <div class="mb-3 form-group">
    <%= f.label :domain_name, class: 'd-block' %>
    <div class="input-group">
      <div class="input-group-text pe-0">
        <%= "http://#{Rails.application.config.x.host_name}/" %>
      </div>
      <%= f.text_field :domain_name, class: "#{render_field_class(@store, :domain_name)} ps-0", disabled: @store.persisted? %>
    </div>
    <%= f.invalid_feedback :domain_name %>
    <%= f.valid_feedback :domain_name %>
  </div>

  <%= f.text_area_form_group :description %>
  <%= f.file_form_group :avatar %>

  <div class="mb-3 form-action">
    <%= f.submit t(:save), class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/stores/_new_item.html.erb
<div class="ms-3">
  <%= @store.name %> doesn't has any items yet.&nbsp;
  <%= link_to_main_modal 'Create new item',
        title: t(:new),
        processor: 'item/fetch-form',
        url: new_store_item_path(@store),
        class: 'btn btn-primary' %>
</div>

app/views/stores/_store.html.erb
<tr>
  <td>
    <%= store.id %>
  </td>
  <td>
    <%- if store.avatar.attached? -%>
      <%= image_tag store.avatar.variant(resize_to_limit: [80, 80]) %>
    <%- else -%>
      <%= image_tag '/default/camera.svg', width: '80px', style: 'opacity:0.1' %>
    <%- end -%>
  </td>
  <td>
    <%= link_to store.name, store_path(store) %>
  </td>
  <td>
    <%= simple_format store.description %>
  </td>
  <td>
    <%= store.items.count %>
  </td>
  <td>
    <%= local_time_ago(store.created_at) %>
  </td>
  <td>
    <div class="btn-group" role="group">
      <%= link_to t(:edit), edit_store_path(store, from: stores_path), class: 'btn btn-outline-primary' %>
      <%= link_to_main_modal t(:delete),
            title: t(:are_you_sure),
            processor: 'store/destroy',
            url: store_path(store),
            method: :delete,
            class: 'btn btn-outline-primary'  %>
    </div>
  </td>
</tr>

app/views/stores/_stores.html.erb
<% if @stores.any? %>
  <%- @stores.each do |store| %>
    <% cache store do %>
      <li>
        <%= link_to store.name, store_path(store), class: 'dropdown-item' %>
      </li>
    <% end %>
  <% end %>
  <li>
    <hr class="dropdown-divider" />
  </li>
  <% if @stores.count == per_page %>
    <li>
      <%= link_to t(:all), stores_path, class: 'dropdown-item' %>
    </li>
  <% else %>
    <li>
      <%= link_to t('stores.create.title'), new_store_path, class: 'dropdown-item' %>
    </li>
  <% end %>
<% else %>
  <li>
    <%= link_to t('stores.create.title'), new_store_path, class: 'btn btn-primary' %>
  </li>
<% end %>

app/views/stores/edit.html.erb
<%- @page_title = [Store.model_name.human(count: 2), t(:edit), @store.name].join(' | ') %>

<%= render_breadcrumbs([link_to(t(:home), root_path), link_to(t(:my_store), stores_path), link_to(@store.name, store_path(@store)), t(:edit)]) %>
<%= render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">
      <%= [t(:edit), @store.name].join(' ') %>
    </h5>
    <div class="row">
      <div class="col-2">
        <%- if @store.avatar.attached? %>
          <%= image_tag @store.avatar.variant(resize_to_limit: [180, 180]) %>
        <% else %>
          <%= image_tag '/default/camera.svg', width: '180px', class: 'me-2', style: 'opacity:0.1' %>
        <% end %>
      </div>
      <div class="col">
        <%= render 'form', local: true, url: store_path(@store) %>
      </div>
    </div>
  </div>
</div>

app/views/stores/edit.js.erb
<%= render 'form', local: false, url: store_path(@store, format: :js) %>

app/views/stores/index.html.erb
<% @page_title = Store.model_name.human(count: 2) %>
<% render_breadcrumbs([link_to_unless_current(t(:home), root_path), t(:my_store)]) %>
<% render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card mb-3">
  <div class="card-body">
    <div class="d-flex align-items-center">
      <h5 class="card-title me-auto"><%= t(:my_store) %></h5>
      <div class="btn-group" role="group" aria-label="<%= Store.model_name.human %>'s actions">
        <button class="btn btn-secondary">
          <i class="bi bi-grid"></i>
        </button>
        <%= link_to_main_modal content_tag(:i, nil, class: 'bi bi-plus'),
              title: t('stores.create.title'),
              processor: 'store/fetch-form',
              url: new_store_path(format: :js),
              class: 'btn btn-primary' %>
      </div>
    </div>
    <table class="table table-hover align-middle">
      <thead>
        <tr>
          <th scope="col">
            <%= Store.human_attribute_name(:id) %>
          </th>
          <th scope="col">
            <%= Store.human_attribute_name(:avatar) %>
          </th>
          <th scope="col">
            <%= Store.human_attribute_name(:name) %>
          </th>
          <th scope="col">
            <%= Store.human_attribute_name(:description) %>
          </th>
          <th scope="col">
            <%= Store.human_attribute_name(:items_count) %>
          </th>
          <th scope="col">
            <%= Store.human_attribute_name(:created_at) %>
          </th>
          <th scope="col">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @stores.each do |store| %>
          <% cache store do %>
            <%= render 'store', store: store %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= render_records_navigation @stores %>
  </div>
</div>
<br />

app/views/stores/index.js.erb
<%= render 'stores' %>

app/views/stores/new.html.erb
<% @page_title = [Store.model_name.human(count: 2), t(:edit), @store.name].join(' | ') %>
<% render_breadcrumbs([link_to(t(:home), root_path), link_to(t(:my_store), stores_path), t(:new), @store.name]) %>
<% render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">
      <%= link_to_back %>&nbsp;<%= t(:new) %>
    </h5>
    <div class="row">
      <div class="col-2">
        <svg width="180" height="180" style="background-color: #eee;">
          <circle cx="90" cy="90" r="40" stroke="white" stroke-width="4" fill="green" />
          Sorry, your browser does not support inline SVG.
        </svg>
      </div>
      <div class="col">
        <%= render 'form', url: stores_path, local: true %>
      </div>
    </div>
  </div>
</div>

app/views/stores/new.js.erb
<%= j(render 'form', local: false, url: stores_path(format: :js)) %>

app/views/stores/show.html.erb
<%- @page_title = [Store.model_name.human, @store.name].join(' | ') %>

<%= render_breadcrumbs([link_to(t(:home), root_path), link_to(t(:my_store), stores_path), @store.name]) %>
<%= render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card mb-3">
  <svg class="img-fluid" width="100%" height="400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="<%= @store.avatar.filename.to_s %>" preserveAspectRatio="xMidYMid slice" focusable="false">
    <% if @store.avatar.attached? %>
      <image href="<%= rails_blob_path(@store.avatar) %>" width="100%" />
    <% end %>
  </svg>

  <div class="card-body">
    <div class="d-flex align-items-start">
      <% if @store.avatar.attached? %>
        <%= image_tag @store.avatar.variant(resize_to_limit: [80, 80]), class: 'me-2' %>
      <%- else -%>
        <%= image_tag '/default/camera.svg', width: '80px', class: 'me-2', style: 'opacity:0.1' %>
      <% end %>
      <div class="me-auto">
        <h5 class="card-title">
          <%= @store.name %>
        </h5>
        <p>
          <%= simple_format @store.description %>
        </p>
      </div>
      <%- if current_user.my_store?(@store) -%>
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <%= link_to_main_modal t(:edit),
                title: t('stores.update.title', name: @store.name),
                processor: 'store/fetch-form',
                url: edit_store_path(@store, format: :js),
                class: 'btn btn-outline-primary' %>
          <%= link_to_main_modal t(:delete),
                title: t(:are_you_sure),
                processor: 'store/destroy',
                url: store_path(@store),
                method: :delete,
                class: 'btn btn-outline-primary'  %>
        </div>
      <% else %>
        <button class="btn btn-link text-decoration-none">
          <%= t(:follow) %>
        </button>
      <% end %>
    </div>
  </div>
</div>

<ul class="nav nav-tabs border-bottom-0">
  <li class="nav-item me-auto">
    <%= link_to content_tag(:strong, Item.model_name.human(count: 2)), '#',
          class: 'nav-link active btn', 'aria-current': 'page' %>
  </li>
  <!--
  <li class="nav-item me-auto">
    <%= link_to content_tag(:strong, 'Review'), '#', class: 'nav-link btn' %>
  </li>
  -->
  <%- if current_user.my_store?(@store) %>
    <li class="nav-item">
      <%= link_to_main_modal 'Add item',
            title: t(:new),
            processor: 'item/fetch-form',
            size: 'lg',
            url: new_store_item_path(@store),
            class: 'btn btn-link text-decoration-none' %>
    </li>
  <% end %>
</ul>

<div class="card border-top-0">
  <div class="card-body">

    <div class="d-flex align-items-start">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <button class="nav-link active"
                id="v-pills-home-tab"
                data-bs-toggle="pill"
                data-bs-target="#v-pills-home"
                type="button"
                role="tab"
                aria-controls="v-pills-home"
                aria-selected="true">
          <%= t(:all) %>
        </button>

        <%- @store.labels.uniq.each do |label| %>
          <button class="nav-link"
            id="v-pills-<%= label.name %>-tab"
            data-bs-toggle="pill"
            data-bs-target="#v-pills-<%= label.name %>"
            type="button"
            role="tab"
            aria-controls="v-pills-<%= label.name %>"
            aria-selected="false"><%= label.name %></button>
        <% end %>
      </div>
      <div class="tab-content w-100" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div class="<%= build_items_classes %>">
              <%- if @items.present? %>
                <%#= render_item_listing(@items, store: false, from_store: true) %>
              <% else %>
                <%= render 'new_item' %>
              <% end %>
            </div>
            <%#= render_records_navigation @items %>
        </div>
        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">...</div>
      </div>
    </div>

  </div>
</div>