config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # mount_devise_token_auth_for 'User', at: 'users', controllers: {
      #   registrations: 'api/v1/users/registrations',
      #   sessions: 'api/v1/users/sessions'
      # }

      resources :items, except: %I[new edit] do
        resources :photos, except: %I[new edit]
      end
    end
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :properties
    resources :stores
    resources :users

    root 'home#index'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callback: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :items, only: %I[index show] do
    collection do
      get :me
      get :following
    end

    resources :photos, module: 'items'
  end
  resources :stores do
    resources :items, module: 'stores'
  end
  resource :account, only: %I[show edit update]
  resource :profile
  resource :setting

  root 'items#index'
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ActionController::Base
    include I18nLocale

    layout 'admin'
  end
end

app/controllers/api/v1/application_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # ApplicationController
    class ApplicationController < ActionController::API
      # before_action :authenticate_api_v1_user!

      # alias current_user current_api_v1_user
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  include I18nLocale

  helper_method :previous_or_current_path

  before_action :set_from_location

  protected

  def set_from_location
    cookies[:from] = params[:from] if params[:from].present?
  end

  def previous_or_current_path(path)
    previous_path = cookies[:from]
    cookies.delete :from
    previous_path.present? ? previous_path : path
  end
end

app/helpers/admin/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module Admin::ApplicationHelper
  def admin_page_title
    title = []
    title << Rails.application.config.x.app_name
    title << t('admin.title')
    title << @page_title if @page_title
    title.compact.join(' | ')
  end

  def render_admin_header
    render 'header'
  end

  def render_admin_breadcrumbs(items)
    content_for :breadcrumbs do
      render 'breadcrumbs', items: items
    end
  end

  def render_admin_main_nav(active)
    content_for :main_nav do
      render 'main_nav', active: active
    end
  end

  def render_admin_page_title(title)
    @page_title = title
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
  def page_title
    title = ['Berjubel']
    title << @page_title
    title.compact.join(' | ')
  end

  def berjubel_logo
    [content_tag(:i, nil, class: 'bi bi-bootstrap-fill fs-3'), Rails.configuration.x.app_name.gsub('B', '')].join('&nbsp;').html_safe
  end

  def body_class
    'class=page-error' if @page_error
  end

  def item_listing_mode
    current_user.try(:setting).try(:listing_mode) || 'column'
  end

  def render_item_listing(items, options = {})
    if items.any?
      render "items/#{item_listing_mode.pluralize}", items: items, options: options
    else
      render 'empty'
    end
  end

  def render_user_name
    current_user.try(:profile).try(:first_name) || current_user.email
  end

  def render_user_avatar
    avatar = current_user.try(:profile).try(:avatar)

    if avatar&.attached?
      image_tag avatar.variant(resize_to_limit: [40, 40], crop: '40x40+0+0')
    else
      image_tag '/default/avatar.svg', width: '34px'
    end
  end

  def render_field_class(object, field)
    return 'form-control is-invalid' if object.errors[field].present?
    return 'form-control is-valid' if object.errors[field].blank? && object[field].present?

    'form-control'
  end

  def render_floating_alert(messages, type = :danger)
    alert_message = if type == :danger
                      render_error_message(messages)
                    else
                      render_success_message(messages)
                    end

    return unless messages.present?

    @page_error = true

    content_for :alert do
      render 'floating_alert', messages: alert_message
    end
  end

  def render_locale_selector(current_path)
    render 'locale_selector', current_path: current_path || 'root_path'
  end

  def link_to_back
    link_to 'javascript:window.history.back()' do
      content_tag(:i, nil, class: 'bi bi-arrow-left')
    end
  end

  def link_to_main_modal(name, options = {})
    link_to name, '#mainModal', main_modal_options(options)
  end

  def link_to_remote_dropdown(name, path, options = {})
    link_to_unless_current name, path, remote_dropdown_options(options)
  end

  private

  def main_modal_options(options = {})
    link_options = {}
    link_options.merge!('data-bs-toggle': :modal)
    link_options.merge!('data-bs-title': options[:title]) if options[:title]
    link_options.merge!('data-bs-processor': options[:processor]) if options[:processor]
    link_options.merge!('data-bs-url': options[:url]) if options[:url]
    link_options.merge!('data-bs-params': options[:params]) if options[:params]
    link_options.merge!('data-bs-method': options[:method]) if options[:method]
    link_options.merge!('data-bs-size': options[:size]) if options[:size]
    link_options.merge!(class: options[:class]) if options[:class]
    link_options
  end

  def remote_dropdown_options(options = {})
    html_class = ['dropdown-toggle']
    html_class << options[:class] if options[:class]

    link_options = {}
    link_options.merge!(class: html_class.join(' '))
    link_options.merge!('data-bs-toggle': 'dropdown')
    link_options.merge!('data-bs-dropdown': 'remote')
    link_options.merge!('data-bs-url': options[:url])
    link_options
  end

  def alerty_types
    %i[primary secondary danger success warning info light dark]
  end
end

app/views/admin/application/_breadcrumbs.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <% items.each do |item| %>
      <li class="breadcrumb-item"><%= item %></li>
    <% end %>
  </ol>
</nav>

app/views/admin/application/_empty.html.erb
<%- messages ||= t(:empty) %>

<div class="alert alert-light mx-auto" role="alert">
  <h3 class="text-muted"><%= messages %></h3>
</div>

app/views/admin/application/_floating_alert.html.erb
<div class="position-relative">
  <div class="position-absolute top-0 start-50 translate-middle floating-alert">
    <%= messages %>
  </div>
</div>

app/views/admin/application/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <p class="col-md-4 mb-0 text-muted">&copy; 2021 Company, Inc</p>

  <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
  </a>

  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
  </ul>
</footer>

app/views/admin/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <strong>
      <%= link_to_unless_current berjubel_logo, admin_root_path, class: 'navbar-brand' do %>
        <span class="navbar-brand"><%= berjubel_logo %></span>
      <% end %>
    </strong>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= yield :search_form %>
      <%= render 'user_nav' %>
    </div>
  </div>
</nav>

app/views/admin/application/_loader.html.erb
<div class="card">
  <div class="card-body">
    <div class="spinner-grow" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>

app/views/admin/application/_main_modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" aria-labelledby="berjubelMainModal" aria-hidden="true" data-bs-backdrop="static">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mainModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Modal body
      </div>
    </div>
  </div>
</div>

app/views/admin/application/_main_nav.html.erb
<% active ||= :home %>

<ul class="nav nav-pills bg-info sticky-top" id="adminNav" role="tablist">
  <li class="nav-item" role="presentation">
    <%= link_to admin_root_path, class: "nav-link rounded-0#{' active' if active == :home}" do %>
      <i class="bi bi-house-door-fill"></i>&nbsp;<%= t(:home) %>
    <% end %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to admin_stores_path, class: "nav-link rounded-0#{' active' if active == :stores}" do %>
      <i class="bi bi-bank2"></i>&nbsp;<%= Store.model_name.human(count: 2) %>
    <% end %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to admin_items_path, class: "nav-link rounded-0#{' active' if active == :items}" do %>
      <i class="bi bi-bag-fill"></i>&nbsp;<%= Item.model_name.human(count: 2) %>
    <% end %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to admin_categories_path, class: "nav-link rounded-0#{' active' if active == :categories}" do %>
      <i class="bi bi-collection-fill"></i>&nbsp;<%= Category.model_name.human(count: 2) %>
    <% end %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to admin_users_path, class: "nav-link rounded-0#{' active' if active == :users}" do %>
      <i class="bi bi-people-fill"></i>&nbsp;<%= User.model_name.human(count: 2) %>
    <% end %>
  </li>
  <li class="nav-item ms-auto" role="presentation">
    <%= link_to admin_properties_path, class: "nav-link rounded-0#{' active' if [:system, :properties].include?(active)}" do %>
      <i class="bi bi-gear-fill"></i>&nbsp;<%= t(:system) %>
    <% end %>
  </li>
</ul>

app/views/admin/application/_placeholder.html.erb
<div class="card" aria-hidden="true">
  <div class="card-body">
    <h5 class="card-title placeholder-glow">
      <span class="placeholder col-6"></span>
    </h5>
    <p class="card-text placeholder-glow">
      <span class="placeholder col-7"></span>
      <span class="placeholder col-4"></span>
      <span class="placeholder col-4"></span>
      <span class="placeholder col-6"></span>
      <span class="placeholder col-8"></span>
    </p>
    <a href="#" tabindex="-1" class="btn btn-primary disabled placeholder col-6"></a>
  </div>
</div>

app/views/admin/application/_records_navigation.html.erb
<div class="row d-flex align-items-center justify-content-between">
  <div class="col-auto">
    <div class="dropdown">
      <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        <%= per_page %>
      </a>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <% available_per_pages.each do |ap| %>
          <li>
            <%= link_to ap, url_for_pagination(ap), class: 'dropdown-item' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-auto">
    <%= paginate records, theme: 'bootstrap_pagination' %>
  </div>
  <div class="col-auto">
    <%= page_entries_info records %>
  </div>
</div>

app/views/admin/application/_success_message.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <div class="d-flex align-items-start">
    <i class="bi bi-emoji-sunglasses me-3 heading-icon"></i>
    <div>
      <h6 class="alert-heading">
        <%= t('messages.good') %>
      </h6>
      <% messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/admin/application/_upper_alert.html.erb
<div id="upper-alert" class="alert-warning p-1" role="alert">
  <strong><%= t(:loading) %>...</strong>
</div>

app/views/admin/application/_user_nav.html.erb
<ul class="navbar-nav d-flex align-items-center ms-auto">
  <li class="dropdown me-3">
    <a href="#">
      <i class="bi bi-bell-fill text-white"></i>
    </a>
  </li>
  <li class="dropdown me-2">
    <a href="#">
      <i class="bi bi-person-fill fs-3 text-white"></i>
    </a>
  </li>
</ul>