config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # mount_devise_token_auth_for 'User', at: 'users', controllers: {
      #   registrations: 'api/v1/users/registrations',
      #   sessions: 'api/v1/users/sessions'
      # }

      resources :items, except: %I[new edit] do
        resources :photos, except: %I[new edit]
      end
    end
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :properties
    resources :stores
    resources :users

    root 'home#index'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callback: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :items, only: %I[index show] do
    collection do
      get :me
      get :following
    end

    resources :photos, module: 'items'
  end
  resources :stores do
    resources :items, module: 'stores'
  end
  resource :account, only: %I[show edit update]
  resource :profile
  resource :setting

  root 'items#index'
end

app/models/store.rb
# frozen_string_literal: true

# Store model
class Store < ApplicationRecord
  include ActivityControl

  belongs_to :user

  has_many :items, dependent: :destroy
  has_many :labels, through: :items
  has_many :categories, through: :items, class_name: 'Category'

  has_one_attached :avatar do |attachable|
    attachable.variant :small, resize: '80x80'
  end

  validates :avatar, blob: { content_type: :image, size_range: 1..5.megabytes }
  # validates :name, :domain_name, uniqueness: true, presence: true
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

module Admin
  # StoresController
  class StoresController < Admin::ApplicationController
    include Pagination

    def index
      @search = Store.ransack(query)
      @stores = @search.result(distinct: true)
                       .page(page)
                       .per(per_page)
                       .order(order)

      respond_to do |format|
        format.html
        format.js
      end
    end

    def show
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html
        format.js
      end
    end

    def new
      @store = Store.new
    end

    def create
      @store = Store.new(store_params)

      respond_to do |format|
        if @store.save
          format.html { redirect_to admin_stores_path, notice: t('.success') }
        else
          format.html { render :new, notice: t('.failed') }
        end
      end
    end

    def edit
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html
        format.js
      end
    end

    def update
      @store = Store.find(params[:id])

      respond_to do |format|
        if @store.update(store_params)
          format.html { redirect_to admin_stores_path, notice: t('.success') }
        else
          format.html { render :edit, notice: t('.failed') }
        end
      end
    end

    def destroy
      @store = Store.find(params[:id])

      respond_to do |format|
        if @store.destroy
          format.html { redirect_to admin_stores_path }
        else
          format.html { redirect_to admin_store_path(@store) }
        end
      end
    end

    private

    def store_params
      params.require(:store).permit(:user_id, :name, :description, :domain_name, :avatar)
    end
  end
end

app/controllers/stores/items_controller.rb
# frozen_string_literal: true

module Stores
  # ItemsController
  class ItemsController < ApplicationController
    include Pagination

    before_action :authenticate_user!
    before_action :find_store, except: :index

    def index
      @store = Store.where(id: params[:store_id]).first

      redirect_to stores_path and return unless @store

      @search = @store.items.ransack(query)
      @items = @search.result(distinct: true)
                      .order(order)
                      .page(page)
                      .per(per_page)
    end

    def show
      @item = @store.items.find(params[:id])

      render 'items/show'
    end

    def new
      @item = @store.items.new

      render partial: 'stores/items/form' if request.xhr?
    end

    def create
      @item = @store.items.new(item_params)

      if @item.save
        redirect_to store_path(@store), notice: t('items.create.success')
      else
        render partial: 'stores/items/form', status: :unprocessable_entity and return if request.xhr?

        render :new
      end
    end

    def edit
      @item = @store.items.find(params[:id])

      render partial: 'stores/items/form' if request.xhr?
    end

    def update
      @item = @store.items.find(params[:id])

      if @item.update(item_params)
        if request.xhr?
          render partial: 'stores/items/form'
        else
          redirect_to store_path(@store), notice: t('items.update.success')
        end
      elsif request.xhr?
        render partial: 'stores/items/form'
      else
        render :edit
      end
    end

    def destroy
      @item = @store.items.find(params[:id])

      notice = @item.destroy ? t('items.destroy.success') : t('items.destroy.failed')

      redirect_to store_path(@store), notice: notice
    end

    private

    def item_params
      params.require(:item).permit(
        :name,
        :description,
        :category_id,
        :label_id,
        item_labels_attributes: %i[id label_id _destroy],
        photos: []
      )
    end

    def find_store
      @store = current_user.stores.where(id: params[:store_id]).first

      respond_to do |format|
        format.html { redirect_to stores_path and return unless @store }
      end
    end
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

# StoresController
class StoresController < ApplicationController
  include Pagination

  before_action :authenticate_user!

  def index
    @search = current_user.stores.ransack(query)

    @stores = @search.result(distinct: true)
                     .order(order)
                     .page(page)
                     .per(per_page)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @store = current_user.stores.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @store = current_user.stores.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_path, notice: t('stores.create.success') }
        format.js { render json: @store.to_json }
      else
        format.html { render :new }
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @store = current_user.stores.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @store = current_user.stores.find(params[:id])
    store_params.delete(:domain_name)

    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to previous_or_current_path(store_path(@store)), notice: t('stores.update.success') }
        format.js { render json: @store.to_json }
      else
        format.html { render :edit }
        format.js { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store = current_user.stores.find(params[:id])

    respond_to do |format|
      if @store.destroy
        format.html { redirect_to stores_path, notice: t('stores.destroy.success') }
      else
        format.html { render stores_path }
      end
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :domain_name, :description, :avatar)
  end
end

app/views/admin/stores/_form.html.erb
<%= form_with model: @store, local: local, url: url, builder: BerjubelFormBuilder, data: { 'bj-remote': !local, 'bj-processor': 'store/validate-form' } do |f| %>
  <%= f.alert %>
  <%= f.select_form_group :user_id, User.all.map{|u| [u.email, u.id]}, include_blank: t('.select_user') %>
  <%= f.text_form_group :name %>
  <%= f.domain_form_group :domain_name %>
  <%= f.text_area_form_group :description %>
  <%= f.check_box_form_group :active %>
  <%= f.file_form_group :avatar %>
  <%= f.action_form_group :save %>
<% end %>

app/views/admin/stores/_tr_body.html.erb
<tr>
  <td>
    <%= store.id %>
  </td>
  <td>
    <%= link_to store.name, admin_store_path(store) %>
  </td>
  <td>
    <%= link_to store.domain_name, ('http://' + Rails.application.config.x.host_name + '/' + store.domain_name), target: :blank if store.domain_name.present? %>
  </td>
  <td>
    <div class="dsc">
      <%= simple_format store.description %>
    </div>
  </td>
  <td>
    <span data-bs-toggle="tooltip" title="<%= store.created_at.to_formatted_s(:long) %>">
      <%= time_ago_in_words(store.created_at) %>
    </span>
  </td>
  <td>
    <span data-bs-toggle="tooltip" title="<%= store.updated_at.to_formatted_s(:long) %>">
      <%= time_ago_in_words(store.updated_at) %>
    </span>
  </td>
  <td>
    <%= I18n.t(store.active?.to_s) %>
  </td>
  <td>
    <div class="btn-group btn-group-sm" role="group" aria-label="User's actions">
      <%= link_to edit_admin_store_path(store), class: 'btn btn-success' do %>
        <i class="bi bi-pencil-fill"></i>
      <% end %>
      <button type="button" class="btn btn-danger"><i class="bi bi-trash-fill"></i></button>
    </div>
  </td>
</tr>

app/views/admin/stores/_tr_head.html.erb
<tr>
  <th scope="col">
    <%= sort_link(@search, :id, {}, { class: 'text-decoration-none' }) %>
  </th>
  <th scope="col">
    <%= sort_link(@search, :name, {}, { class: 'text-decoration-none' }) %>
  </th>
  <th scope="col">
    <%= sort_link(@search, :domain_name, {}, { class: 'text-decoration-none' }) %>
  </th>
  <th scope="col">
    <%= Store.human_attribute_name(:description) %>
  </th>
  <th scope="col">
    <%= sort_link(@search, :created_at, {}, { class: 'text-decoration-none' }) %>
  </th>
  <th scope="col">
    <%= sort_link(@search, :updated_at, {}, { class: 'text-decoration-none' }) %>
  </th>
  <th scope="col">
    <%= sort_link(@search, :active, {}, { class: 'text-decoration-none' }) %>
  </th>
  <th scope="col">
  </th>
</tr>

app/views/admin/stores/edit.html.erb
<% render_admin_page_title([t(:edit), @store.name].join(' | ')) %>
<% render_admin_main_nav(:stores) %>
<% render_admin_breadcrumbs([
  link_to(t(:home), admin_root_path),
  link_to(Store.model_name.human(count: 2), admin_stores_path),
  link_to(@store.name, admin_store_path(@store)),
  t(:edit)
]) %>

<div class="d-flex justify-content-between align-items-center my-2">
  <h3><%= link_to_back %>&nbsp;<%= t(:edit) %></h3>
  <%= link_to t(:cancel), admin_stores_path, class: 'btn btn-link' %>
</div>

<div class="card">
  <div class="card-body">
    <%= render 'form', url: admin_store_path(@store), local: true %>
  </div>
</div>

app/views/admin/stores/index.html.erb
<% render_admin_page_title(Store.model_name.human(count: 2)) %>
<% render_admin_main_nav(:stores) %>
<% render_floating_alert([flash.now[:notice]].compact, :success) %>
<% render_admin_breadcrumbs([link_to(t(:home), admin_root_path), Store.model_name.human(count: 2)]) %>

<% content_for :search_form do %>
  <form>
    <input type="search" class="form-control border-bottom">
  </form>
<% end %>

<div class="d-flex justify-content-between align-items-center my-2">
  <h3><%= Store.model_name.human(count: 2) %></h3>
  <div class="btn-group" role="group" aria-label="Actions">
    <button class="btn btn-secondary">
      <i class="bi bi-search"></i>
    </button>
    <button class="btn btn-danger">
      <i class="bi bi-caret-down"></i>
    </button>
    <button class="btn btn-primary">
      <i class="bi bi-grid"></i>
    </button>
    <%= link_to new_admin_store_path, class: 'btn btn-success' do %>
      <i class="bi bi-plus"></i>
    <% end %>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <%= render 'tr_head' %>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <%= render 'tr_body', store: store %>
    <% end %>
  </tbody>
</table>

<%= render_records_navigation @stores %>

app/views/admin/stores/new.html.erb
<% render_admin_page_title([t(:new), Store.model_name.human(count: 2)].join(' | ')) %>
<% render_admin_main_nav(:stores) %>
<% render_admin_breadcrumbs([link_to(t(:home), admin_root_path), link_to(Store.model_name.human(count: 2), admin_stores_path), t(:new)]) %>

<div class="d-flex justify-content-between align-items-center my-2">
  <h3><%= link_to_back %>&nbsp;<%= t(:new) %></h3>
  <%= link_to t(:cancel), admin_stores_path, class: 'btn btn-link' %>
</div>

<div class="card">
  <div class="card-body">
    <%= render 'form', local: true, url: admin_stores_path %>
  </div>
</div>

app/views/admin/stores/show.html.erb
<% render_admin_page_title(@store.name) %>
<% render_admin_main_nav(:stores) %>
<% render_admin_breadcrumbs([link_to(t(:home), admin_root_path), link_to(Store.model_name.human(count: 2), admin_stores_path), @store.name]) %>

<div class="d-flex justify-content-between align-items-center my-2">
  <h3><%= link_to_back %>&nbsp;<%= @store.name %></h3>
  <div class="btn-group" role="group" aria-label="Store's actions">
    <%= link_to edit_admin_store_path(@store), class: 'btn btn-success' do %>
      <i class="bi bi-pencil-fill"></i>
    <% end %>
    <button type="button" class="btn btn-danger"><i class="bi bi-trash-fill"></i></button>
  </div>
</div>

<div class="card">
  <%= image_tag @store.avatar, class: 'card-img-top' %>
  <div class="card-body">
    <%= simple_format @store.description %>
  </div>
</div>