config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # mount_devise_token_auth_for 'User', at: 'users', controllers: {
      #   registrations: 'api/v1/users/registrations',
      #   sessions: 'api/v1/users/sessions'
      # }

      resources :items, except: %I[new edit] do
        resources :photos, except: %I[new edit]
      end
    end
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :properties
    resources :stores
    resources :users

    root 'home#index'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callback: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :items, only: %I[index show] do
    collection do
      get :me
      get :following
    end

    resources :photos, module: 'items'
  end
  resources :stores do
    resources :items, module: 'stores'
  end
  resource :account, only: %I[show edit update]
  resource :profile
  resource :setting

  root 'items#index'
end

app/models/item.rb
# frozen_string_literal: true

# Item model
class Item < ApplicationRecord
  include ActivityControl

  belongs_to :category
  belongs_to :store
  belongs_to :user

  has_many_attached :photos

  has_many :prices, inverse_of: :item, dependent: :destroy
  has_many :item_properties
  has_many :properties, through: :item_properties
  has_many :item_labels
  has_many :labels, through: :item_labels

  accepts_nested_attributes_for :labels
  accepts_nested_attributes_for :prices

  # validates :photos, blob: { content_type: :image, size_range: 1..10.megabytes }
  validates :name, :description, presence: true

  before_validation do |record|
    record.user = record.store.try(:user) unless record.user
  end

  ransack_alias :all, :name_or_description

  def default_photo
    photos.first
  end
end

app/models/item/label.rb
# frozen_string_literal: true

class Item::Label < ApplicationRecord
  belongs_to :store
  belongs_to :item
  belongs_to :label
end

app/models/item/variant.rb
# frozen_string_literal: true

class Item::Variant < ApplicationRecord
  belongs_to :item
end

app/models/store.rb
# frozen_string_literal: true

# Store model
class Store < ApplicationRecord
  include ActivityControl

  belongs_to :user

  has_many :items, dependent: :destroy
  has_many :labels, through: :items
  has_many :categories, through: :items, class_name: 'Category'

  has_one_attached :avatar do |attachable|
    attachable.variant :small, resize: '80x80'
  end

  validates :avatar, blob: { content_type: :image, size_range: 1..5.megabytes }
  # validates :name, :domain_name, uniqueness: true, presence: true
end

app/controllers/admin/items_controller.rb
# frozen_string_literal: true

module Admin
  # ItemsController
  class ItemsController < Admin::ApplicationController
    include Pagination

    def index
      @search = Item.ransack(query)
      @items = @search.result(distinct: true)
                      .includes(:store)
                      .page(page)
                      .per(per_page)
                      .order(order)

      respond_to do |format|
        format.html
      end
    end
  end
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

module Admin
  # StoresController
  class StoresController < Admin::ApplicationController
    include Pagination

    def index
      @search = Store.ransack(query)
      @stores = @search.result(distinct: true)
                       .page(page)
                       .per(per_page)
                       .order(order)

      respond_to do |format|
        format.html
        format.js
      end
    end

    def show
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html
        format.js
      end
    end

    def new
      @store = Store.new
    end

    def create
      @store = Store.new(store_params)

      respond_to do |format|
        if @store.save
          format.html { redirect_to admin_stores_path, notice: t('.success') }
        else
          format.html { render :new, notice: t('.failed') }
        end
      end
    end

    def edit
      @store = Store.find(params[:id])

      respond_to do |format|
        format.html
        format.js
      end
    end

    def update
      @store = Store.find(params[:id])

      respond_to do |format|
        if @store.update(store_params)
          format.html { redirect_to admin_stores_path, notice: t('.success') }
        else
          format.html { render :edit, notice: t('.failed') }
        end
      end
    end

    def destroy
      @store = Store.find(params[:id])

      respond_to do |format|
        if @store.destroy
          format.html { redirect_to admin_stores_path }
        else
          format.html { redirect_to admin_store_path(@store) }
        end
      end
    end

    private

    def store_params
      params.require(:store).permit(:user_id, :name, :description, :domain_name, :avatar)
    end
  end
end

app/controllers/api/v1/items/photos_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Items
      # PhotosController
      class PhotosController < Api::V1::ApplicationController
        before_action :find_item

        def index
          @photos = @item.photos
        end

        private

        def find_item
          @item = Item.where(id: params[:item_id]).first

          redirect_to items_path and return unless @item
        end
      end
    end
  end
end

app/controllers/api/v1/items_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # ItemsController
    class ItemsController < Api::V1::ApplicationController
      include Pagination

      def index
        @search = Item.ransack(query)

        @items = @search.result(distinct: true)
                        .order(order)
                        .page(page)
                        .per_page(per_page)
      end

      def create
        @item = current_user.items.new(item_params)

        if @item.save
          render json: @item.as_json
        else
          render json: { status: :unprocessable_entity, data: @item.errors.messages }
        end
      end

      private

      def item_params
        params.require(:item).permit!(:name, :description)
      end
    end
  end
end

app/controllers/items/photos_controller.rb
# frozen_string_literal: true

module Items
  # PhotosController
  class PhotosController < ApplicationController
    include Pagination

    before_action :find_item

    def index
      @photos = @item.photos
                     .ransack(query)
                     .result(distinct: true)
                     .order(order)
                     .page(page)
                     .per(per_page)

      render partial: 'carousel' and return if request.xhr?
    end

    private

    def find_item
      @item = Item.where(id: params[:item_id]).first

      redirect_to items_path and return unless @item
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# ItemsController
class ItemsController < ApplicationController
  # include Authentication
  include Pagination

  def index
    @search = Item.active.ransack(query)
    load_items

    respond_to do |format|
      format.html
    end
  end

  def show
    @item = Item.active.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def following
    @search = Item.active.ransack(query)
    load_items

    respond_to do |format|
      format.html { render :index }
    end
  end

  def me
    @search = Item.active.ransack(user_id_eq: current_user.id)
    load_items

    respond_to do |format|
      format.html { render :index }
    end
  end

  private

  def load_items
    @items = @search.result(distinct: true)
                    .includes(:store)
                    .page(page)
                    .per(per_page)
                    .order(order)
  end
end

app/controllers/stores/items_controller.rb
# frozen_string_literal: true

module Stores
  # ItemsController
  class ItemsController < ApplicationController
    include Pagination

    before_action :authenticate_user!
    before_action :find_store, except: :index

    def index
      @store = Store.where(id: params[:store_id]).first

      redirect_to stores_path and return unless @store

      @search = @store.items.ransack(query)
      @items = @search.result(distinct: true)
                      .order(order)
                      .page(page)
                      .per(per_page)
    end

    def show
      @item = @store.items.find(params[:id])

      render 'items/show'
    end

    def new
      @item = @store.items.new

      render partial: 'stores/items/form' if request.xhr?
    end

    def create
      @item = @store.items.new(item_params)

      if @item.save
        redirect_to store_path(@store), notice: t('items.create.success')
      else
        render partial: 'stores/items/form', status: :unprocessable_entity and return if request.xhr?

        render :new
      end
    end

    def edit
      @item = @store.items.find(params[:id])

      render partial: 'stores/items/form' if request.xhr?
    end

    def update
      @item = @store.items.find(params[:id])

      if @item.update(item_params)
        if request.xhr?
          render partial: 'stores/items/form'
        else
          redirect_to store_path(@store), notice: t('items.update.success')
        end
      elsif request.xhr?
        render partial: 'stores/items/form'
      else
        render :edit
      end
    end

    def destroy
      @item = @store.items.find(params[:id])

      notice = @item.destroy ? t('items.destroy.success') : t('items.destroy.failed')

      redirect_to store_path(@store), notice: notice
    end

    private

    def item_params
      params.require(:item).permit(
        :name,
        :description,
        :category_id,
        :label_id,
        item_labels_attributes: %i[id label_id _destroy],
        photos: []
      )
    end

    def find_store
      @store = current_user.stores.where(id: params[:store_id]).first

      respond_to do |format|
        format.html { redirect_to stores_path and return unless @store }
      end
    end
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

# StoresController
class StoresController < ApplicationController
  include Pagination

  before_action :authenticate_user!

  def index
    @search = current_user.stores.ransack(query)

    @stores = @search.result(distinct: true)
                     .order(order)
                     .page(page)
                     .per(per_page)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @store = current_user.stores.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @store = current_user.stores.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_path, notice: t('stores.create.success') }
        format.js { render json: @store.to_json }
      else
        format.html { render :new }
        format.js { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @store = current_user.stores.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @store = current_user.stores.find(params[:id])
    store_params.delete(:domain_name)

    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to previous_or_current_path(store_path(@store)), notice: t('stores.update.success') }
        format.js { render json: @store.to_json }
      else
        format.html { render :edit }
        format.js { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store = current_user.stores.find(params[:id])

    respond_to do |format|
      if @store.destroy
        format.html { redirect_to stores_path, notice: t('stores.destroy.success') }
      else
        format.html { render stores_path }
      end
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :domain_name, :description, :avatar)
  end
end

app/helpers/item_helper.rb
# frozen_string_literal: true

# ItemHelper
module ItemHelper
  def build_items_classes
    if item_listing_mode == 'list'
      'd-flex flex-column'
    else
      'd-flex align-content-stretch flex-wrap justify-content-between'
    end
  end

  def render_item_action(item, options = {})
    render 'item_change', item: item, options: options if current_user.my_store?(item.store)
  end

  def render_listing_items_selector
    render 'listing_mode_form'
  end

  def render_nested_categories(categories)
    render 'stores/items/nested_category', categories: categories
  end

  def render_nested_category_path(category)
    nested_category_path(category).compact.reverse.join(' &rArr; ').html_safe if category
  end

  def nested_category_path(category)
    return unless category

    categories = [category.translated_name]
    categories += nested_category_path(category.parent) if category.parent?
    categories
  end
end

app/views/stores/items/_form.html.erb
<%- local ||= false %>
<%- url = @item.persisted? ? store_item_path(@store, @item) : store_items_path(@store) %>

<%= form_with model: @item, url: url, local: local, builder: BerjubelFormBuilder do |f| %>
  <%= f.alert %>
  <%= f.text_form_group :name, placeholder: t('.name.placeholder'), autofocus: true %>
  <%= f.select_form_group :category_id, grouped_options_for_select(Category.to_nested_array, f.object.category_id), { prompt: t('.placeholder') } %>

  <div class="mb-3 form-group">
    <%= f.label :label_id %>
    <%= f.select :label_id, [], { prompt: t('.label_id.placeholder') }, class: 'form-control' %>
  </div>

  <%= f.text_area_form_group :description, placeholder: t('.description.placeholder'), rows: 10 %>
  <%= f.file_form_group :photos, multiple: true %>

  <div class="form-group">
    <%- f.object.photos.each do |p| %>
      <div class="position-relative d-inline-block m-2">
        <button class="btn position-absolute top-0 end-0" style="font-size:0.6rem;">&#10006;</button>
        <%= image_tag(p.variant(resize_to_limit: [80, 80])) %>
      </div>
    <% end %>
  </div>

  <div class="mb-3 form-action">
    <%= f.submit t(:save), class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/stores/items/_nested_category.html.erb
<% path_ids ||= [] %>

<ul class="dropdown-menu">
  <% categories.each do | category| %>
    <%- children = category.children %>
    <li class="dropdown <%= 'dropend' if children.present? %> <%= 'active' if path_ids.include?(category.id) %>">
      <span
        class="dropdown-item <%= 'dropdown-toggle' if children.present? %>"
        data-bs-toggle="dropdown"
        data-value="<%= category.id %>"
        data-label="<%= category.translated_name %>"
        data-path="<%= [category.parent.try(:translated_name), category.translated_name].compact.join(' &rArr; ').html_safe %>">
        <%= category.translated_name %>
      </span>
      <%= render 'stores/items/nested_category', categories: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/stores/items/edit.html.erb
<%- @page_title = [Item.model_name.human, @item.name].join(' | ') %>

<%= render_breadcrumbs([
  link_to(t(:home), root_path),
  link_to(t(:my_store), stores_path),
  link_to(@store.name, store_path(@store)),
  @item.name,
  t(:edit)
]) %>
<%= render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card">
  <div class="card-body">
    <div class="d-flex align-items-center">
      <h5 class="card-title me-auto">
        <%= [t(:edit), content_tag(:i, @item.name)].join(' ').html_safe %>
      </h5>
      <%= link_to t(:cancel), :back, class: 'btn btn-link' %>
    </div>
    <%= render 'form', local: true %>
  </div>
</div>

app/views/stores/items/index.html.erb
<%- @page_title = [Store.model_name.human, @store.name, Item.model_name.human(count: 2)].join(' | ') %>

<%= render_breadcrumbs([
  link_to(t(:home), root_path),
  link_to(Store.model_name.human(count: 2), stores_path),
  @store.name,
  Item.model_name.human(count: 2)
]) %>

<%= render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card">
  <div class="card-body">
    <%#= image_tag @store.avatar %>
    <h5 class="card-title">
      <%= link_to '&#8629;'.html_safe, :back %> <%= @store.name %>
    </h5>
    <p>
      <%= @store.description %>
    </p>
    <h5>
      <%= Item.model_name.human(count: 2) %>
    </h5>
    <table class="table">
      <tr>
        <th><%= Item.human_attribute_name(:id) %></th>
        <th><%= Item.human_attribute_name(:name) %></th>
      </tr>
      <%- @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.name %></td>
        </tr>
      <%- end %>
    </table>
    <%= will_paginate(@items, renderer: BerjubelPagination) %>
  </div>
</div>

app/views/stores/items/new.html.erb
<%- @page_title = Item.model_name.human %>

<%= render_breadcrumbs([
  link_to(t(:home), root_path),
  link_to(t(:my_store), stores_path),
  link_to(@store.name, store_path(@store)),
  Item.model_name.human(count: 2),
  t(:new)
]) %>
<%= render_floating_alert([flash.now[:notice]].compact, :success) %>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">
      <%= Item.model_name.human %>
    </h5>
    <%= render 'form', local: true %>
  </div>
</div>